package com.maxrave.domain.data.entities.analytics

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.maxrave.domain.extension.now
import kotlinx.datetime.LocalDateTime

/**
 * One play, and the table every analytics figure in the app is derived from.
 *
 * It carried NO index at all while `event_artist`, its own child, carried three — so all twenty
 * queries that read it were full table scans over a table that only ever grows.
 *
 * The shape of the two indices was measured, not reasoned, and the obvious choice was wrong.
 * A plain `(timestamp)` index makes the NARROW windows fast (a 7-day top-tracks goes 2.9 ms to
 * 0.6, a month's count 2.5 to 0.09) and the WIDE ones SLOWER — a year-long range selects half the
 * table, where seeking the index and then fetching each row beats a straight scan only in theory:
 * "top tracks, 1 year" went 18.4 ms to 26.4, and the Wrapped sample scan 16.2 to 26.0. Adding
 * `videoId` alone does not fix it (26.4 and 25.6, the same regression, and already 4.1 MB of the
 * 4.2 the full index costs). `listenedSecond` is what does: with it the wide queries read the
 * index and never touch the table at all, landing at 15.5 ms and 13.9 — faster than having no
 * index — while every narrow win is kept. Measured on 58 400 rows, two years at ~80 plays a day.
 *
 * The second index, on `videoId`, serves the two places that match ids rather than time:
 * `queryAlreadyPlayed`'s `IN` (11.8 ms to 0.08) and the `NOT IN` subquery behind Rediscover.
 *
 * What is deliberately NOT indexed. `eventId`: an autogenerated `Long` primary key IS the SQLite
 * rowid, so the join from `event_artist` is already a rowid lookup. `albumBrowseId`: never
 * filtered on its own, always beside a `timestamp` range that has narrowed the rows first. An
 * index costs a write on every play and space in the file, so one that would rarely be chosen is
 * a cost with no return — the two here add ~2.5 MB per 58 400 plays and about a microsecond per
 * insert, which is below the noise of the measurement.
 *
 * Rediscover is the one query these barely help (36.7 ms to 35.7): it groups most of the table
 * and then runs a `NOT IN` subquery over it, so there is no selective range to seek with.
 */
@Entity(
    "playback_event",
    indices = [
        Index(value = ["timestamp", "videoId", "listenedSecond"]),
        Index(value = ["videoId"]),
    ],
)
data class PlaybackEventEntity(
    @PrimaryKey(autoGenerate = true) val eventId: Long = 0,
    val timestamp: LocalDateTime = now(),
    val videoId: String = "",
    val albumBrowseId: String? = null,
    val durationSecond: Long = 0, // 0 - 100
    val listenedSecond: Long = 0, // in seconds
)